### ISSUE TITLE
Change the position of the loading bar

### ISSUE THREAD

**Issue by Alestore** [TurboWarp/packager#541]
I am thinking of taking advantage of the background of the initial loading when starting the exported project by modifying it by inserting an animated gif. The only problem is that in this gif I want to insert some readable text, and the loading bar located in the center is not very helpful, I would like to move it to the bottom right. Is it possible to do it?

**Comment by GarboMuffin** [comment]
Custom CSS

```css
.progress-bar-outer {
  position: fixed;
  bottom: 10px;
  right: 10px;
}
```
